//! Code generation library for Hermes errors.
//!
//! This library generates contract-specific error files from the canonical
//! error registry, ensuring a single source of truth for all error
//! definitions and stability snapshots.
//!
//! # Usage
//!
//! In a contract's `build.rs`:
//!
//! ```ignore
//! use hermes_codegen::GenerateErrors;
//! use hermes_errors::all_errors;
//!
//! fn main() {
//!     let out_dir = std::env::var("OUT_DIR").unwrap();
//!     let errors = all_errors()
//!         .into_iter()
//!         .filter(|e| e.scope.contains("analytics"))
//!         .collect();
//!
//!     GenerateErrors::new("analytics", &errors)
//!         .generate_errors_rs(&out_dir)
//!         .generate_err_stab_rs(&out_dir);
//! }
//! ```

use hermes_errors::ErrorDefinition;
use std::path::Path;

pub struct GenerateErrors {
    contract_name: String,
    errors: Vec<ErrorDefinition>,
}

impl GenerateErrors {
    pub fn new(contract_name: &str, errors: &[ErrorDefinition]) -> Self {
        Self {
            contract_name: contract_name.to_string(),
            errors: errors.to_vec(),
        }
    }

    /// Generate the main error definition file (Rust enum).
    ///
    /// Output: `{contract}/src/errors.rs` (generated at compile time in OUT_DIR)
    pub fn generate_errors_rs(&self, out_dir: &str) -> String {
        let out_path = Path::new(out_dir).join("errors.rs");

        let mut content = format!(
            "//! Error types for the {} contract.\n\
             //!\n\
             //! This file is **generated** from the canonical error registry in\n\
             //! `crates/hermes-errors/src/lib.rs`. Do NOT edit this file directly;\n\
             //! update the registry and regenerate.\n\
             //!\n\
             //! # Stability guarantee\n\
             //!\n\
             //! Once a code appears in a deployed version it **must not** be renumbered,\n\
             //! removed, or reused for a different meaning without an explicit versioning\n\
             //! decision and a corresponding migration note in the PR description.\n\
             //!\n\
             //! New variants must be appended with a fresh, previously-unused code.  The\n\
             //! stability snapshot in `tests/err_stab.rs` will fail to compile until the\n\
             //! addition is deliberately registered there.\n\
             \n\
             use soroban_sdk::contracterror;\n\
             \n\
             /// Errors returned by the {} contract.\n\
             ///\n\
             /// Each variant is assigned an explicit `u32` discriminant that forms part of\n\
             /// the contract's **client-facing API surface**.\n",
            self.contract_name, self.contract_name
        );

        // Build code range documentation
        let mut ranges: Vec<(u32, u32)> = Vec::new();
        for err in &self.errors {
            if let Some(range) = err.range {
                if !ranges.iter().any(|r| r == &range) {
                    ranges.push(range);
                }
            }
        }
        ranges.sort();

        if !ranges.is_empty() {
            content.push_str("///\n/// Code ranges:\n");
            for (min, max) in ranges {
                content.push_str(&format!("/// * `{}`–`{}`\n", min, max));
            }
        }

        content.push_str(
            "#[contracterror]\n\
             #[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]\n\
             #[repr(u32)]\n\
             pub enum ContractError {\n",
        );

        for err in &self.errors {
            content.push_str(&format!(
                "    /// {}\n    {} = {},\n",
                err.description, err.name, err.code
            ));
        }

        content.push_str("}\n");

        // Write file
        std::fs::write(&out_path, content).expect("Failed to write errors.rs");

        out_path.to_string_lossy().to_string()
    }

    /// Generate the error stability snapshot test file.
    ///
    /// Output: `{contract}/tests/err_stab.rs` (generated at compile time)
    pub fn generate_err_stab_rs(&self, out_dir: &str) -> String {
        let out_path = Path::new(out_dir).join("err_stab.rs");

        let mut content = format!(
            "//! {} `ContractError` stability snapshot.\n\
             //!\n\
             //! This file is **generated** from the canonical error registry.\n\
             //! Do NOT edit this file directly; update the registry and regenerate.\n\
             //!\n\
             //! # Purpose\n\
             //!\n\
             //! `ContractError` discriminants are serialized by the Soroban SDK and\n\
             //! consumed directly by off-chain analytics dashboards, indexers, and\n\
             //! monitoring tooling.  Any change to an existing code number is therefore\n\
             //! a **client-facing API break** that requires an explicit migration decision\n\
             //! and a corresponding note in the PR description.\n\
             //!\n\
             //! # Rules for contributors\n\
             //!\n\
             //! * **Never renumber** an existing variant.\n\
             //! * **Never remove** a variant (deprecate instead, document in the PR).\n\
             //! * **Never reuse** a code that belonged to a removed variant.\n\
             //! * New variants must be **appended** with a fresh, previously-unused code.\n\
             //! * Adding a new variant requires updating the canonical registry and\n\
             //!   regenerating this file.  The compiler will reject an incomplete match,\n\
             //!   preventing silent omissions.\n\
             \n\
             use std::collections::BTreeSet;\n\
             \n",
            self.contract_name
        );

        // Macro definition
        content.push_str(
            "macro_rules! error_code_snapshot {\n\
             ($($variant:ident = $code:literal),+ $(,)?) => {{\n\
             const ERROR_CODE_SNAPSHOT: &[(&str, u32)] = &[\n\
             $((stringify!($variant), $code),)+\n\
             ];\n\
             \n\
             fn frozen_code(name: &str, code: u32) -> u32 {\n\
             code\n\
             }\n\
             }}\n\
             }\n\
             \n",
        );

        // Build the snapshot macro call
        let mut snapshot_call = "error_code_snapshot! {\n".to_string();
        for err in &self.errors {
            snapshot_call.push_str(&format!("    {} = {},\n", err.name, err.code));
        }
        snapshot_call.push_str("}\n\n");
        content.push_str(&snapshot_call);

        // Tests
        content.push_str(&format!(
            "#[test]\n\
             fn {} _error_codes_are_unique() {{\n\
             let codes = vec![\n",
            self.contract_name
        ));

        for err in &self.errors {
            content.push_str(&format!("        {},\n", err.code));
        }

        content.push_str(
            "    ];\n\
             let mut seen = std::collections::BTreeSet::new();\n\
             for code in codes {\n\
             assert!(seen.insert(code), \"Duplicate error code: {{}}\", code);\n\
             }\n\
             }\n",
        );

        // Write file
        std::fs::write(&out_path, content).expect("Failed to write err_stab.rs");

        out_path.to_string_lossy().to_string()
    }
}
